version: 2
jobs:
  build:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - run: xcodebuild clean build -project "Calendar.xcodeproj" -scheme "Calendar" -sdk iphonesimulator

workflows:
  version: 2
  build:
    jobs:
      - build
