name: Calendar-Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean build -project "Calendar.xcodeproj" -scheme "Calendar" -sdk iphonesimulator
